LLM Serving patterns first wave
GoogleCloudPlatform/apigee-samples pull request #170
Opened 2024-09-23 03:50 UTC by ra2085

2024-09-23 23:45 UTC, drush1980 requested changes

2024-09-23 23:45 UTC, drush1980 commented on llm-logging/llm-extraxt-candidates-v1/llm-extract-candidates-v1.xml
Parent folder is spelled incorrectly i.e. `llm-extraxt-candidates-v1` -> `llm-extract-candidates-v1`

2024-09-23 23:45 UTC, drush1980 commented on llm-token-limits/llm_token_limits.ipynb
> +        "Apigee allows you to create a tiered product strategy with different API access levels (e.g., Bronze, Bronze, Goals) to cater to diverse user needs and limits. During the [Setup](#setup) sta
Was `(e.g., Bronze, Bronze, Goals)` supposed to be something like `(e.g., Bronze, Silver, Gold)`?

2024-09-23 23:45 UTC, drush1980 commented on llm-token-limits/llm_token_limits.ipynb
> +        "* If using the **Silver Key**, fhe final token count (sum of tokens from prompts and response candates) shouldn't exceed the Silver AI Product tokens limit of 5000 tokens every 5 minutoes.\n
`candates` -> `candidates`?
`minutoes` -> `minutes`

2024-09-23 23:45 UTC, drush1980 commented on llm-token-limits/llm_token_limits.ipynb
> +        "This scenario demonstrates a basic interaction with a language model. The code repeatedly asks a language model the same question, \"Why is the sky blue?\" but phrased in different ways to m
`onnce` -> `once`

2024-09-23 23:45 UTC, drush1980 commented on llm-token-limits/llm_token_limits.ipynb
> +        "* If using the **Bronze Key**, fhe final token count (sum of tokens from prompts and response candates) **should exceed** the Bronze AI Product tokens limit of 2000 tokens every 5 minutoes.
`candates` -> `candidates`?
`minutoes` -> `minutes`
`SHoud should` -> `Should`

2024-09-23 23:45 UTC, drush1980 commented on llm-token-limits/llm_token_limits.ipynb
> +        "* If using the **Silver Key**, fhe final token count (sum of tokens from prompts and response candates) shouldn't exceed the Silver AI Product tokens limit of 5000 tokens every 5 minutoes."
`candates` -> `candidates`?
`minutoes` -> `minutes`

2024-09-24 02:04 UTC, ra2085 reviewed
applied all proposed fixes.

2024-09-24 02:12 UTC, drush1980 approved these changes
lgtm

2024-09-24 02:12 UTC, merged