merge extract-variables accelerator
GoogleCloudPlatform/apigee-samples pull request #75
Opened 2023-08-18 16:40 UTC by egonzalezpozega

Adding accelerator to showcase extract-variables and assign message policies

2023-08-21 21:50 UTC, drush1980 requested changes

2023-08-21 21:50 UTC, drush1980 commented on extract-variables/README.md
> +This sample shows how to easily extract fields from an XML and JSON response. For this sample I will be leveraging the following policies:
I'd avoid writing in the first person.  Maybe change to `This sample leverages the following policies:`

2023-08-21 21:50 UTC, drush1980 commented on extract-variables/README.md
> +After extracting the specified message content, you can reference the variable in other policies as part of processing a request and response.
Perhaps add a link to more info about flow variables and point to [this doc](https://cloud.google.com/apigee/docs/api-platform/fundamentals/introduction-flow-variables).

2023-08-21 21:50 UTC, drush1980 commented on extract-variables/README.md
> +[![Alt text](https://img.youtube.com/vi/ep7h_tGHtiw/0.jpg)](https://www.youtube.com/watch?v=ep7h_tGHtiw)
Remove this section until video is ready

2023-08-21 21:50 UTC, drush1980 commented on extract-variables/README.md
> +3. Access to deploy proxies, create products, apps and developers in Apigee
This sample doesn't appear to require products, apps or developers

2023-08-21 21:50 UTC, drush1980 commented on extract-variables/README.md
> +If you want to clean up the artefacts from this example in your Apigee Organization, first source your `env.sh` script, and then run
`artefacts` -> `artifacts`

2023-08-21 21:50 UTC, drush1980 commented on extract-variables/apiproxy/policies/AM-Set-Headers.xml
> +      <Header name="target.ip">{target.ip}</Header>
I don't think we need to set all these variables as headers. I'd just set the ones below which were extracted in the previous steps.

2023-08-21 21:50 UTC, drush1980 commented on extract-variables/docs/cloudshell-tutorial.md
> +Navigate to the `basic-quota` directory in the Cloud shell.
`basic-quota` -> `extract-variables`

2023-08-21 21:50 UTC, drush1980 commented on extract-variables/docs/cloudshell-tutorial.md
> +Next, let's create and deploy the Apigee resources necessary to test the quota policy.
Replace `quota`

2023-08-21 21:50 UTC, drush1980 commented on extract-variables/docs/cloudshell-tutorial.md
> +This script creates a sample API Proxy, a Developer, two API products, and two Apps. The script also tests that the deployment and configuration has been sucessful.
This sample doesn't create developers, products or apps

2023-08-21 21:50 UTC, drush1980 commented on extract-variables/docs/cloudshell-tutorial.md
> +2. Use the JavaScript policy to read the variables so that they show in the debug tool.
JS policy is not implemented in this sample

2023-08-21 21:50 UTC, drush1980 commented on extract-variables/docs/cloudshell-tutorial.md
> +5. Use the JavaScript policy again to read the variables so that they show in the debug tool.
JS policy is not implemented in this sample

2023-08-21 21:50 UTC, drush1980 commented on extract-variables/docs/cloudshell-tutorial.md
> +If you want to clean up the artefacts from this example in your Apigee Organization, first source your `env.sh` script, and then run
`artefacts` -> `artifacts`

2023-08-22 01:02 UTC, egonzalezpozega commented
@drush1980  I have added all the suggested changes

2023-08-22 16:40 UTC, drush1980 commented on extract-variables/README.md
> +curl https://$APIGEE_HOST/v1/samples/extract-variables
small suggestion: add the `-v` flag so the user can see the headers returned in the response

2023-08-22 16:40 UTC, drush1980 commented on extract-variables/docs/cloudshell-tutorial.md
> +curl https://$APIGEE_HOST/v1/samples/extract-variables
small suggestion: add the -v flag so the user can see the headers returned in the response

2023-08-22 16:42 UTC, drush1980 approved these changes
Added a couple of small suggestions, but otherwise lgtm

2023-08-22 17:03 UTC, egonzalezpozega commented
all suggested fixes done.

2023-08-22 18:45 UTC, ssvaidyanathan commented
@drush1980 - lets merge if you think we are good

2023-08-22 20:01 UTC, merged